test_lab2:
  image: ipadsse302/tigerlabs_score_env
  tags:
    - r743
  stage: test
  script:
    - rm -rf scripts testdata
    - cp -r /home/stu/upload.py /home/stu/scripts /home/stu/testdata .
    - make gradelab2
